### ISSUE TITLE
Confusion in ReadMe.md

### ISSUE THREAD

**Issue by degaurab** [pivotal-cf/gcp-concourse#6]
Hi Customer-0
The comment Readme regarding DNS entry in step 7-8 seems little confusing. As we saw that DNS terraform step is not part of `init-iaas` any more and moved to `deploy-iaas`.
So it seems confusing and we are not sure how it actually work if we dont update the NameServer entries (in AWS Route 53) on the fly.
So it would be great if you can please update the Readme with the details. 

Gaurab & @lojoe

**Comment by virtmerlin** [comment]
@degaurab sorry its been a bit for me to look at this.   The readme only applies to the 'c0-gcp-concourse-poc.yml' pipeline variant which basically removes any trigger links from the init-env job to the deploy-iaas job for an intentional pause.  This is done so that an operator running the pipeline for a POC can use any DNS service and be provided with the IPs they will need for A/CNAME records.   If you look at the 'ci/pipeline-variants/c0-gcp-concourse-base-ci.yml' pipeline variant,  we simply added an additional task to the init-env job to use DYN for this purpose in an automated fashion.   That approach doesn't even use the GCP managed zone at all, its just creating it for doc purposes really.    We will be refactoring the pipelines very soon and will prob move creating the managed dns zone for GCP (Azure & AWS too) as part of the init-iaas job(s) as well so a DNS delegation could be used to refer to the GCP nameservers from a Route 53 registered domain ... or anywhere really,  as it stands now, using the GCP managed zone would have to occur at the end of the deploy-iaas job as you have already noted, but could be done similarly to the DYN integration task.  Not sure if the readme is inaccurate on this as its not requiring the use of the GCP managed DNS zone,  but id be happy to edit it if u have a suggestion :)

**Comment by krishicks** [comment]
Closing this as it is no longer applicable. The README has been updated to reflect the many changes that happened to the pipeline.
